### ISSUE TITLE
mysql5.7默认字符集默认utf8mb3，导致标题带有emoji报错

### ISSUE THREAD

**Issue by banjuer** [luchenqun/my-bookmark#35]
#### 以下为报错网站`https://emojixd.com/`书签报错信息
```log
Error: ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect string value: '\xF0\x9F\xA4\xA3 E...' for column 'title' at row 1
    at Query.Sequence._packetToError (/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/app/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/app/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/app/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/app/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Socket.<anonymous> (/app/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/app/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:309:12)
    --------------------
    at Protocol._enqueue (/app/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at PoolConnection.query (/app/node_modules/mysql/lib/Connection.js:198:25)
    at /app/node_modules/think-helper/index.js:83:10
    at new Promise (<anonymous>)
    at /app/node_modules/think-helper/index.js:82:12
    at ThinkMysql.[think-mysql-query] (/app/node_modules/think-mysql/index.js:169:12)
    at /app/node_modules/think-mysql/index.js:247:25
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: 'ER_TRUNCATED_WRONG_VALUE_FOR_FIELD',
  errno: 1366,
  sqlMessage: "Incorrect string value: '\\xF0\\x9F\\xA4\\xA3 E...' for column 'title' at row 1",
  sqlState: 'HY000',
  index: 0,
  sql: "INSERT INTO `bookmarks` (`userId`,`tagId`,`title`,`url`,`clickCount`,`createdAt`,`lastClick`) VALUES (2,2,'🤣 Emoji表情大全，颜文字百科  - EmojiXD','https://emojixd.com/',1,'2022-03-15 03:14:11','2022-03-26 09:19:36')"
```
#### 如何解决？
1. 修改书签，去掉emoji表情。  **治标不治本**
2. 修改mysql5.7默认字符集为`utf8mb4`。可以参考这篇博客：`https://www.lovesofttech.com/database/mysql5.7ToUtf8mb4.html`

**Comment by banjuer** [comment]
BTW, 这个项目很棒，天才般的想法！以前只遇到过书签同步迁移等问题，没想过去怎么解决
