### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by selierlin** [luchenqun/my-bookmark#9]
在执行完 npm install ,接下来我使用命令 node ./bin/www，出现错误如下：

[root@izuf69vcnr1ik26qj06t0cz my-bookmark]# node ./bin/www
/root/my-bookmark/routes/api.js:1225
    let downloadFavicon = async () => {
                                ^
SyntaxError: Unexpected token (
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/my-bookmark/app.js:10:11)
    at Module._compile (module.js:556:32)

nodejs：v6.6.0
mysql：v5.7.24

**Comment by selierlin** [comment]
已经解决，更改nodejs的版本解决，我nodejs版本是8.11
